// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTask(arg1:main.CreateTaskInput):Promise<main.Task>;

export function ExportBackup():Promise<string>;

export function GetState():Promise<main.AppState>;

export function GetTaskTimeSummary(arg1:string):Promise<main.TaskTimeSummary>;

export function ImportBackup():Promise<string>;

export function SetTaskCompleted(arg1:string,arg2:boolean):Promise<void>;

export function StartTimer(arg1:string):Promise<void>;

export function StopTimer(arg1:string):Promise<void>;
