// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTaskTimeSummary(arg1) {
  return window['go']['main']['App']['GetTaskTimeSummary'](arg1);
}

export function ImportBackup() {
  return window['go']['main']['App']['ImportBackup']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function ResumeTimer() {
  return window['go']['main']['App']['ResumeTimer']();
}

export function SetTaskCompleted(arg1, arg2) {
  return window['go']['main']['App']['SetTaskCompleted'](arg1, arg2);
}

export function StartTimer(arg1) {
  return window['go']['main']['App']['StartTimer'](arg1);
}

export function StopTimer(arg1) {
  return window['go']['main']['App']['StopTimer'](arg1);
}
